### ISSUE TITLE
`:simple_one_for_one` strategy deprecation warnings when running in Elixir v1.10

### ISSUE THREAD

**Issue by Manzanit0** [CrowdHailer/Ace#140]
When upgrading my project from Elixir 1.9 to 1.10 I started getting the below warnings. I imagine due to [this](https://hexdocs.pm/elixir/DynamicSupervisor.html#module-migrating-from-supervisors-simple_one_for_one).

```
12:30:17.803 [info]  Serving securely using ["h2", "http/1.1"] on port 8080
warning: :simple_one_for_one strategy is deprecated, please use DynamicSupervisor instead
  (elixir 1.10.0) lib/supervisor.ex:604: Supervisor.init/2
  (elixir 1.10.0) lib/supervisor.ex:556: Supervisor.start_link/2
  (ace 0.18.9) lib/ace/http/service.ex:247: Ace.HTTP.Service.init/1
  (stdlib 3.10) gen_server.erl:374: :gen_server.init_it/2
  (stdlib 3.10) gen_server.erl:342: :gen_server.init_it/6

warning: :simple_one_for_one strategy is deprecated, please use DynamicSupervisor instead
  (elixir 1.10.0) lib/supervisor.ex:604: Supervisor.init/2
  (elixir 1.10.0) lib/supervisor.ex:556: Supervisor.start_link/2
  (ace 0.18.9) lib/ace/http/service.ex:254: Ace.HTTP.Service.init/1
  (stdlib 3.10) gen_server.erl:374: :gen_server.init_it/2
  (stdlib 3.10) gen_server.erl:342: :gen_server.init_it/6

warning: :simple_one_for_one strategy is deprecated, please use DynamicSupervisor instead
  (elixir 1.10.0) lib/supervisor.ex:604: Supervisor.init/2
  (elixir 1.10.0) lib/supervisor.ex:556: Supervisor.start_link/2
  (ace 0.18.9) lib/ace/http/service.ex:262: Ace.HTTP.Service.init/1
  (stdlib 3.10) gen_server.erl:374: :gen_server.init_it/2
  (stdlib 3.10) gen_server.erl:342: :gen_server.init_it/6
```

**Comment by filipecabaco** [comment]
Opened PR that cleans up deprecation warnings.

https://github.com/CrowdHailer/Ace/pull/141

**Comment by CrowdHailer** [comment]
Thanks for the PR @filipecabaco this is definitely the right approach
