### ISSUE TITLE
Un-handled cases causes match errors. 

### ISSUE THREAD

**Issue by tckb** [CrowdHailer/Ace#56]
hey, firstoff thanks for starting a pure elixir project for http/2 support. there are some great erlang libs but given that I'm new erlang/elixir I find this much more convienient. 

I'm using **Ace** for writing a http/2 server to handle some of the requests that are coming in. During my tests, I found couple of cases which are not handled, at least not _that_ well.
This results some of the ugly messages such as 

```
10:08:29.740 [error] GenServer #PID<0.247.0> terminating
** (MatchError) no match of right hand side value: {:error, :closed}
    (ace) lib/ace/http2/connection.ex:242: Ace.HTTP2.Connection.do_send_frames/2
    (ace) lib/ace/http2/connection.ex:114: Ace.HTTP2.Connection.handle_info/2
    (stdlib) gen_server.erl:616: :gen_server.try_dispatch/4
    (stdlib) gen_server.erl:686: :gen_server.handle_msg/6
    (stdlib) proc_lib.erl:247: :proc_lib.init_p_do_apply/3
Last message: :timeout
State: {:listening, {:sslsocket, nil, {#Port<0.7082>, {:config, {:ssl_options, :tls, [{3, 3}, {3, 2}, {3, 1}], :verify_none, {#Function<8.18432334/3 in :ssl.handle_verify_options/2>, []}, #Function<9.18432334/1 in :ssl.handle_verify_options/2>, false, false, :undefined, 1,"<<REDACTED>>", :undefined, "<<REDACTED>>", :undefined, [], :undefined, "", :undefined, :undefined, :undefined, :undefined, :undefined, [<<192, 44>>, <<192, 48>>, <<192, 36>>, <<192, 40>>, <<192, 46>>, <<192, 50>>, <<192, 38>>, <<192, 42>>, <<0, 159>>, <<0, 163>>, <<0, 107>>, <<0, 106>>, <<0, 157>>, <<0, 61>>, <<192, 43>>, <<192, 47>>, <<192, 35>>, <<192, 39>>, <<192, ...>>, <<...>>, ...], #Function<2.18432334/4 in :ssl.handle_options/3>, true, 268435456, false, true, :infinity, false, :undefined, ["h2", "http/1.1"], :undefined, :undefined, true, :undefined, [], :undefined, false, true, :one_n_minus_one, :undefined, false, ...}, [active: false, mode: :binary, packet: :raw, reuseaddr: true], #PID<0.246.0>, :undefined, [reuseaddr: true, packet_size: 0, packet: 0, header: 0, active: false, mode: :binary], {:gen_tcp, :tcp, :tcp_closed, :tcp_error}, :tls_connection}}}, #PID<0.248.0>, %Ace.HTTP2.Settings{enable_push: false, initial_window_size: 65535, max_concurrent_streams: 10000, max_frame_size: 16384}}
10:08:29.741 [error] GenServer #PID<0.248.0> terminating
```

my log files are full of such messages which are the results for unhandled cases.

Here are the ones I've identified during _timeouts_:
*defmodule Ace.HTTP2.Connection*
`def handle_info(:timeout, {:listening, listen_socket, stream_supervisor, local_settings})`
### Scenario#1 
_Connection close error_ because client has terminated connection w/o sending any data even before SSL negotiation. 

Reproduce:

I encountered this while testing my server using `cURL` (poor me didn't know that curl doesn't support http/2). try 

```
$ curl https://localhost:8443/ping 
<<hangs>>
[cntrl+c to terminate] 
```
the above will raise `{:error, :closed}` at `:ssl.ssl_accept(socket)` instead of `:ok`
### Scenario#2
_Connection close error_ when the connection is still open(?) on the client but  gets terminated on the server _before_ the timeout. When the client tries to send any frame after the termination you'd see another  `{:error, :closed}` 

Reproduce:
restart the server after initial request. Curiously, I've noticed this only in chrome. 

### Scenario#3
_Protocol negotiation failed_  during SSL negotiation between client and server.  For some reasons, a simple health check from AWS LB fails causing `{:error, :protocol_not_negotiated}` 

the likely-hood of the above cases might be less nevertheless, should be handled by the lib. @CrowdHailer  your thoughts?

**Comment by CrowdHailer** [comment]
Hi, thanks for the comprehensive feedback. I have noticed that when I run the h2spec some recent changes introduced a lot more noise into the logs. Interestingly no new tests failed so in someways I love the robustness of erlang that all these unhandled edge cases can be take in it's stride.

Absolutely all these cases should be handled. Normal operation should not add any warning or error messages to the logs. So far I have prioritised getting the API right, but I think I'm pretty much there so should have time to checking these errors soon.

If you could open a PR with failing tests for these scenarios, that would certainly speed me up in tackling them? number 2 looks the most odd. To make it even simpler open a PR with test case for just scenario 1 and we can tackle them one at a time

*Aside. Can I ask, are you using the latest version of Ace and making use of `Raxx.Server`?*

**Comment by tckb** [comment]
@CrowdHailer  indeed fault tolerance of OTP is why I started in Erlang/Elixir. I haven't tried running a h2spec yet. yes, soon enough I'll send out a PR for these scenarios  (I've noticed #2 more than a couple of times actually) I'll try to write formal test cases for it.  

Yes, I'm using `Raxx.Server`. There was a bit confusion at the beginning but, I found my way around.

**Comment by CrowdHailer** [comment]
@tckb would you be able to confirm which of this issues are still present in the latest version of Ace?

**Comment by tckb** [comment]
@CrowdHailer haven't had time to go recheck it. will do it let you know 👍

**Comment by CrowdHailer** [comment]
@tckb alright cool.

**Comment by CrowdHailer** [comment]
Closing due to inactivity. Certainly feel free comment if issues can be reproduced
