### ISSUE TITLE
 (FunctionClauseError) no function clause matching in :lib.is_op/2

### ISSUE THREAD

**Issue by samphilipd** [CrowdHailer/Ace#73]
We're seeing this occasionally in the logs. Doesn't seem to be correlated with anything:

```
(FunctionClauseError) no function clause matching in :lib.is_op/2

Exception(most recent call first)

Elixir.FunctionClauseError: no function clause matching in :lib.is_op/2
  File "lib/rested/router.ex", line 19, in Rested.Router.handle_head/2
  File "lib/ace/http/worker.ex", line 24, in Ace.HTTP.Worker.handle_info/2
  File "gen_server.erl", line 616, in :gen_server.try_dispatch/4
  File "gen_server.erl", line 686, in :gen_server.handle_msg/6
  File "proc_lib.erl", line 247, in :proc_lib.init_p_do_apply/3
  Module "Elixir.Ace.HTTP.Worker", in Ace.HTTP.Worker.init/1
```

More detail:

```
Dec  4 11:17:24 dc1-live-appserver1 eggl[21496]: ** (FunctionClauseError) no function clause matching in Rested.Router.handle_head/2
Dec  4 11:17:24 dc1-live-appserver1 eggl[21496]:     (rested) lib/rested/router.ex:19: Rested.Router.handle_head(%Raxx.Request{authority: "localhost:8081", body: false, headers: [{"user-agent", "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_6) AppleWebKit/537.36 (KHTML,
like Gecko) Chrome/62.0.3202.94 Safari/537.36"}, {"accept", "image/webp,image/apng,image/*,*/*;q=0.8"}, {"referer", "http://localhost:8081/status"}, {"accept-encoding", "gzip, deflate, br"}, {"accept-language", "en-GB,en-US;q=0.9,en;q=0.8"}], method: :GET, mount: [], pa
th: ["favicon.ico"], query: %{}, scheme: :https}, [])
Dec  4 11:17:24 dc1-live-appserver1 eggl[21496]:     (ace) lib/ace/http/worker.ex:24: Ace.HTTP.Worker.handle_info/2
Dec  4 11:17:24 dc1-live-appserver1 eggl[21496]:     (stdlib) gen_server.erl:616: :gen_server.try_dispatch/4
Dec  4 11:17:24 dc1-live-appserver1 eggl[21496]:     (stdlib) gen_server.erl:686: :gen_server.handle_msg/6
Dec  4 11:17:24 dc1-live-appserver1 eggl[21496]:     (stdlib) proc_lib.erl:247: :proc_lib.init_p_do_apply/3
Dec  4 11:17:24 dc1-live-appserver1 eggl[21496]: Last message: {{:http1, #PID<0.4491.0>, 1}, %Raxx.Request{authority: "localhost:8081", body: false, headers: [{"user-agent", "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/62.0.3202.94 Safari/537.36"}, {"accept", "image/webp,image/apng,image/*,*/*;q=0.8"}, {"referer", "http://localhost:8081/status"}, {"accept-encoding", "gzip, deflate, br"}, {"accept-language", "en-GB,en-US;q=0.9,en;q=0.8"}], method: :GET, mount: [], path: ["favicon.ico"], query: %{}, scheme: :https}}
Dec  4 11:17:24 dc1-live-appserver1 eggl[21496]: State: {Rested.Router, [], nil}
Dec  4 11:17:24 dc1-live-appserver1 eggl[21496]: =CRASH REPORT==== 4-Dec-2017::11:17:24 ===
Dec  4 11:17:24 dc1-live-appserver1 eggl[21496]:   crasher:
Dec  4 11:17:24 dc1-live-appserver1 eggl[21496]:     initial call: Elixir.Ace.HTTP.Worker:init/1
Dec  4 11:17:24 dc1-live-appserver1 eggl[21496]:     pid: <0.4527.0>
Dec  4 11:17:24 dc1-live-appserver1 eggl[21496]:     registered_name: []
Dec  4 11:17:24 dc1-live-appserver1 eggl[21496]:     exception error: no function clause matching
Dec  4 11:17:24 dc1-live-appserver1 eggl[21496]:                      'Elixir.Rested.Router':handle_head(#{'__struct__' =>
Dec  4 11:17:24 dc1-live-appserver1 eggl[21496]:                                                               'Elixir.Raxx.Request',
Dec  4 11:17:24 dc1-live-appserver1 eggl[21496]:                                                           authority =>
Dec  4 11:17:24 dc1-live-appserver1 eggl[21496]:                                                               <<"localhost:8081">>,
Dec  4 11:17:24 dc1-live-appserver1 eggl[21496]:                                                           body => false,
Dec  4 11:17:24 dc1-live-appserver1 eggl[21496]:                                                           headers =>
Dec  4 11:17:24 dc1-live-appserver1 eggl[21496]:                                                               [{<<"user-agent">>,
Dec  4 11:17:24 dc1-live-appserver1 eggl[21496]:                                                                 <<"Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/62.0.3202.94 Safari/537.36">>},
Dec  4 11:17:24 dc1-live-appserver1 eggl[21496]:                                                                {<<"accept">>,
Dec  4 11:17:24 dc1-live-appserver1 eggl[21496]:                                                                 <<"image/webp,image/apng,image/*,*/*;q=0.8">>},
Dec  4 11:17:24 dc1-live-appserver1 eggl[21496]:                                                                {<<"referer">>,
Dec  4 11:17:24 dc1-live-appserver1 eggl[21496]:                                                                 <<"http://localhost:8081/status">>},
Dec  4 11:17:24 dc1-live-appserver1 eggl[21496]:                                                                {<<"accept-encoding">>,
Dec  4 11:17:24 dc1-live-appserver1 eggl[21496]:                                                                 <<"gzip, deflate, br">>},
Dec  4 11:17:24 dc1-live-appserver1 eggl[21496]:                                                                {<<"accept-language">>,
Dec  4 11:17:24 dc1-live-appserver1 eggl[21496]:                                                                 <<"en-GB,en-US;q=0.9,en;q=0.8">>}],
Dec  4 11:17:24 dc1-live-appserver1 eggl[21496]:                                                           method => 'GET',
Dec  4 11:17:24 dc1-live-appserver1 eggl[21496]:                                                           mount => [],
Dec  4 11:17:24 dc1-live-appserver1 eggl[21496]:                                                           path =>
Dec  4 11:17:24 dc1-live-appserver1 eggl[21496]:                                                               [<<"favicon.ico">>],
Dec  4 11:17:24 dc1-live-appserver1 eggl[21496]:                                                           query => #{},
Dec  4 11:17:24 dc1-live-appserver1 eggl[21496]:                                                           scheme => https},
Dec  4 11:17:24 dc1-live-appserver1 eggl[21496]:                                                         []) (lib/rested/router.ex, line 19)
Dec  4 11:17:24 dc1-live-appserver1 eggl[21496]:       in function  'Elixir.Ace.HTTP.Worker':handle_info/2 (lib/ace/http/worker.ex, line 24)
Dec  4 11:17:24 dc1-live-appserver1 eggl[21496]:       in call from gen_server:try_dispatch/4 (gen_server.erl, line 616)
Dec  4 11:17:24 dc1-live-appserver1 eggl[21496]:       in call from gen_server:handle_msg/6 (gen_server.erl, line 686)
Dec  4 11:17:24 dc1-live-appserver1 eggl[21496]:     ancestors: [<0.2422.0>,'Elixir.Rested.Router.ClearText',
Dec  4 11:17:24 dc1-live-appserver1 eggl[21496]:                   'Elixir.Rested.Supervisor',<0.2419.0>]
Dec  4 11:17:24 dc1-live-appserver1 eggl[21496]:     message_queue_len: 0
Dec  4 11:17:24 dc1-live-appserver1 eggl[21496]:     messages: []
Dec  4 11:17:24 dc1-live-appserver1 eggl[21496]:     links: [<0.2422.0>]
Dec  4 11:17:24 dc1-live-appserver1 eggl[21496]:     dictionary: []
Dec  4 11:17:24 dc1-live-appserver1 eggl[21496]:     trap_exit: false
Dec  4 11:17:24 dc1-live-appserver1 eggl[21496]:     status: running
Dec  4 11:17:24 dc1-live-appserver1 eggl[21496]:     heap_size: 610
Dec  4 11:17:24 dc1-live-appserver1 eggl[21496]:     stack_size: 27
Dec  4 11:17:24 dc1-live-appserver1 eggl[21496]:     reductions: 293
Dec  4 11:17:24 dc1-live-appserver1 eggl[21496]:   neighbours:
Dec  4 11:17:24 dc1-live-appserver1 eggl[21496]: =SUPERVISOR REPORT==== 4-Dec-2017::11:17:24 ===
Dec  4 11:17:24 dc1-live-appserver1 eggl[21496]:      Supervisor: {<0.2422.0>,'Elixir.Supervisor.Default'}
Dec  4 11:17:24 dc1-live-appserver1 eggl[21496]:      Context:    child_terminated
Dec  4 11:17:24 dc1-live-appserver1 eggl[21496]:      Reason:     {function_clause,
Dec  4 11:17:24 dc1-live-appserver1 eggl[21496]:                      [{'Elixir.Rested.Router',handle_head,
Dec  4 11:17:24 dc1-live-appserver1 eggl[21496]:                           [#{'__struct__' => 'Elixir.Raxx.Request',
Dec  4 11:17:24 dc1-live-appserver1 eggl[21496]:                              authority => <<"localhost:8081">>,body => false,
Dec  4 11:17:24 dc1-live-appserver1 eggl[21496]:                              headers =>
Dec  4 11:17:24 dc1-live-appserver1 eggl[21496]:                                  [{<<"user-agent">>,
Dec  4 11:17:24 dc1-live-appserver1 eggl[21496]:                                    <<"Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/62.0.3202.94 Safari/537.36">>},
Dec  4 11:17:24 dc1-live-appserver1 eggl[21496]:                                   {<<"accept">>,
Dec  4 11:17:24 dc1-live-appserver1 eggl[21496]:                                    <<"image/webp,image/apng,image/*,*/*;q=0.8">>},
Dec  4 11:17:24 dc1-live-appserver1 eggl[21496]:                                   {<<"referer">>,
Dec  4 11:17:24 dc1-live-appserver1 eggl[21496]:                                    <<"http://localhost:8081/status">>},
Dec  4 11:17:24 dc1-live-appserver1 eggl[21496]:                                   {<<"accept-encoding">>,
Dec  4 11:17:24 dc1-live-appserver1 eggl[21496]:                                    <<"gzip, deflate, br">>},
Dec  4 11:17:24 dc1-live-appserver1 eggl[21496]:                                   {<<"accept-language">>,
Dec  4 11:17:24 dc1-live-appserver1 eggl[21496]:                                    <<"en-GB,en-US;q=0.9,en;q=0.8">>}],
Dec  4 11:17:24 dc1-live-appserver1 eggl[21496]:                              method => 'GET',mount => [],
Dec  4 11:17:24 dc1-live-appserver1 eggl[21496]:                              path => [<<"favicon.ico">>],
Dec  4 11:17:24 dc1-live-appserver1 eggl[21496]:                              query => #{},scheme => https},
Dec  4 11:17:24 dc1-live-appserver1 eggl[21496]:                            []],
Dec  4 11:17:24 dc1-live-appserver1 eggl[21496]:                           [{file,"lib/rested/router.ex"},{line,19}]},
Dec  4 11:17:24 dc1-live-appserver1 eggl[21496]:                       {'Elixir.Ace.HTTP.Worker',handle_info,2,
Dec  4 11:17:24 dc1-live-appserver1 eggl[21496]:                           [{file,"lib/ace/http/worker.ex"},{line,24}]},
Dec  4 11:17:24 dc1-live-appserver1 eggl[21496]:                       {gen_server,try_dispatch,4,
Dec  4 11:17:24 dc1-live-appserver1 eggl[21496]:                           [{file,"gen_server.erl"},{line,616}]},
Dec  4 11:17:24 dc1-live-appserver1 eggl[21496]:                       {gen_server,handle_msg,6,
Dec  4 11:17:24 dc1-live-appserver1 eggl[21496]:                           [{file,"gen_server.erl"},{line,686}]},
Dec  4 11:17:24 dc1-live-appserver1 eggl[21496]:                       {proc_lib,init_p_do_apply,3,
Dec  4 11:17:24 dc1-live-appserver1 eggl[21496]:                           [{file,"proc_lib.erl"},{line,247}]}]}
Dec  4 11:17:24 dc1-live-appserver1 eggl[21496]:      Offender:   [{pid,<0.4527.0>},
Dec  4 11:17:24 dc1-live-appserver1 eggl[21496]:                   {id,'Elixir.Ace.HTTP.Worker'},
Dec  4 11:17:24 dc1-live-appserver1 eggl[21496]:                   {mfargs,{'Elixir.Ace.HTTP.Worker',start_link,undefined}},
Dec  4 11:17:24 dc1-live-appserver1 eggl[21496]:                   {restart_type,temporary},
Dec  4 11:17:24 dc1-live-appserver1 eggl[21496]:                   {shutdown,500},
Dec  4 11:17:24 dc1-live-appserver1 eggl[21496]:                   {child_type,worker}]
```

**Comment by CrowdHailer** [comment]
Does this still happen. in the latest version. looking at this it could have been related to processes staying around too long

**Comment by CrowdHailer** [comment]
@samphilipd so this is the issue that you cleared up implementing a 404 handler or no?

**Comment by samphilipd** [comment]
@CrowdHailer it appears to have fixed it, although I'd prefer to wait a week before being sure.

**Comment by CrowdHailer** [comment]
@samphilipd cool, well I'm away this week so if it's all quite please close. thanks

**Comment by CrowdHailer** [comment]
@samphilipd closing this seams sensible now
