### ISSUE TITLE
Updating to 0.16.1 results in Ace reporting errors 

### ISSUE THREAD

**Issue by nietaki** [CrowdHailer/Ace#97]
With the most bare-bones setup with `Ace.HTTP.Service`, updating from 0.16.0 to 0.16.1 causes Ace to spit out some errors (while still serving responses seemingly ok):

```
12:52:51.566 [info]  Serving cleartext using HTTP/1 on port 8080
[]

12:52:54.126 [error] GenServer #PID<0.573.0> terminating
** (stop) exited in: GenServer.call(#PID<0.374.0>, {:send, %Ace.HTTP.Channel{endpoint: #PID<0.374.0>, id: 1, socket: {:tcp, #Port<0.11519>}}, [%Raxx.Response{body: "foo\nbar\nbaz", headers: [], status: 200}]}, 5000)
    ** (EXIT) normal
    (elixir) lib/gen_server.ex:834: GenServer.call/3
    (ace) lib/ace/http/worker.ex:114: Ace.HTTP.Worker.do_send/2
    (stdlib) gen_server.erl:616: :gen_server.try_dispatch/4
    (stdlib) gen_server.erl:686: :gen_server.handle_msg/6
    (stdlib) proc_lib.erl:247: :proc_lib.init_p_do_apply/3
Last message: {%Ace.HTTP.Channel{endpoint: #PID<0.374.0>, id: 1, socket: {:tcp, #Port<0.11519>}}, %Raxx.Request{authority: "localhost:8080", body: false, headers: [{"cache-control", "max-age=0"}, {"upgrade-insecure-requests", "1"}, {"user-agent", "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/65.0.3325.181 Safari/537.36"}, {"accept", "text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,image/apng,*/*;q=0.8"}, {"accept-encoding", "gzip, deflate, br"}, {"accept-language", "en-GB,en;q=0.9,pl;q=0.8"}, {"cookie", "_merchant_key=SFMyNTY.g3QAAAAEbQAAAAtfY3NyZl90b2tlbm0AAAAYWjc4S0xRTURJci9BRU5BbWNiMWVVdz09bQAAAANmb29tAAAAJGVlMjhlN2VjLTJiMDQtNDViNy05MjdmLTJkMWE2Njk4NjFkZW0AAAAWZ3VhcmRpYW5fZGVmYXVsdF90b2tlbm0AAAFwZXlKaGJHY2lPaUpJVXpVeE1pSXNJblI1Y0NJNklrcFhWQ0o5LmV5SmhkV1FpT2lKRGRYSnNJaXdpWlhod0lqb3hOVEkyTWprME1EWTVMQ0pwWVhRaU9qRTFNak00TnpRNE5qa3NJbWx6Y3lJNklrTjFjbXdpTENKcWRHa2lPaUkzTkdWbVlUY3paQzAxTVdGaUxUUTNNemd0T1ROaU9TMWpaVFZoWldNNU1qaGxOMk1pTENKdVltWWlPakUxTWpNNE56UTROamdzSW5OMVlpSTZJalU1WVRobE9XTmhMVGRsTlRNdE5EZ3pNQzA1WWpVMkxUVTVNbVl3TnpWbU5qbGtaaUlzSW5SNWNDSTZJbUZqWTJWemN5SjkuTFJlTHFPaUk5TmxyeVhvYlp6Q3dmS0xhSWhURnF4U3R6bDd4bmozU3c3U0J0TGV6bUFqNXNTNXBTeXBDOU4zT2w0ajQ3ZzlPWmw3ZjQyUGVIMzZUa1FtAAAAEWxvZ2dlZF9pbl91c2VyX2lkbQAAACQ1OWE4ZTljYS03ZTUzLTQ4MzAtOWI1Ni01OTJmMDc1ZjY5ZGY.5MKxHb_v9FWQQKLJZKAl-LbBxj_jIpg_I3jm2lG0TZE"}], method: :GET, mount: [], path: ["s", "ping"], query: nil, scheme: :http}}
State: %Ace.HTTP.Worker{app_module: Suffixer.Web, app_state: [], channel: %Ace.HTTP.Channel{endpoint: #PID<0.374.0>, id: 1, socket: {:tcp, #Port<0.11519>}}, channel_monitor: #Reference<0.543873150.3643801602.90494>}
```

Full repro here: https://github.com/nietaki/suffixer/commit/e10a773a050f62e35bf463b579377dcf5f804ed2 - running unchanged works ok, changing ace version to 0.16.1 causes the error to appear.

I can't really investigate right now, so just leaving this issue here.

**Comment by CrowdHailer** [comment]
I think this should no longer be the case with `0.16.2` which has just been published :whale:
